version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run: |
          apt-get install sshpass
      # - checkout
      # - node/with-cache:
      #     steps:
      #       - run: npm install
      #       - run: npm test
  deploy:
    machine:
      enabled: true
    steps:
       - run:
          name: Deploy Over SSH
          command: |
           sshpass -p "$SSH_USER_PASS" ssh $SSH_USER@$SSH_HOST "cd /var/www/ && rm -rf $APP_FOLDER && git clone https://github.com/topogigiovanni/piral-service.git $APP_FOLDER && cd $APP_FOLDER && sh post_deployment.sh "

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch
